### ISSUE TITLE
Omnienergy fails to load when combined with Bob's power

### ISSUE THREAD

**Issue by SqFKYo** [OmnissiahZelos/omnimatter#10]
Causes either this:
![image](https://user-images.githubusercontent.com/26864304/76681027-e9f92180-65f6-11ea-8855-6744551a7a90.png)

Or boiler-3 similar issue.

**Comment by Samuel2507** [comment]
Seems like an Omniscience issue, working fine without

**Comment by Samuel2507** [comment]
Cant reproduce with current Versions of ABZ

**Comment by SqFKYo** [comment]
Fixed in #34
