### ISSUE TITLE
Bob's steam phase support

### ISSUE THREAD

**Issue by SqFKYo** [OmnissiahZelos/omnimatter#103]
Currently with full omni Bob's steam phase is generally skipped.
The following entity/recipe additions are proposed:
Steam omnitractor
Steam omniphlog
Low yield omniwaste -> omniwater recipe (burner/steam omnitractor only)

**Comment by infantryman4life** [comment]
thats sounds good :)

**Comment by SqFKYo** [comment]
Working on this, moving some early omnic water/water/omniplant recipes to Steam SP when needed.
Planning to get the steam omnitractor/omniphlog done too.

**Comment by SqFKYo** [comment]
Early water/omniplant is in DEV. No real idea how to get steam omnitractor/omniphlog made. Tried coyping burner and reassigning energy, but it seems it's bit complicated.

**Comment by Pezzawinkle** [comment]
What else needs doing before this issue can be closed?

**Comment by SqFKYo** [comment]
Would love that omnitrator/omniphlog that would work on steam. Bob's steam assembling machine and/or bob's fluid burner should help, but it's hard to combine with BuildGen...
