### ISSUE TITLE
Clown's Nuclear crashes with new Omnimatter

### ISSUE THREAD

**Issue by SqFKYo** [OmnissiahZelos/omnimatter#114]
![image](https://user-images.githubusercontent.com/26864304/79140013-ffad6280-7dbf-11ea-8452-0691f347167f.png)
No other mods, just Clown's Vanilla Nuclear and Omnimatter
Looks like yet another icon error.

I'm guessing this might be related to omnimatter/prototypes/extraction-dynamic.lua and RecChain there.

**Comment by Pezzawinkle** [comment]
patched in latest omnilib #118
