### ISSUE TITLE
Omnienergy crashing with deadlock-integrations

### ISSUE THREAD

**Issue by Samuel2507** [OmnissiahZelos/omnimatter#124]
looks a bit like a recipe standardisation issue since energy is not changing anything on higher tier belts at all

![unknown](https://user-images.githubusercontent.com/62474527/79370897-bee65280-7f53-11ea-837e-8b6c58975856.png)

**Comment by SqFKYo** [comment]
Reported to deadlock the two lines of code in bob.lua he should update and added deadlock's integration support to omnienergy.
