### ISSUE TITLE
BuildGen() Furnace Icons supersized on recipe tooltips

### ISSUE THREAD

**Issue by Samuel2507** [OmnissiahZelos/omnimatter#130]
![image](https://user-images.githubusercontent.com/62474527/79585797-99328800-80d0-11ea-9458-a69cb20d35bf.png)

Found with Omnimatter,crystal,energy and basic AB

caused by BuildGen
![image](https://user-images.githubusercontent.com/62474527/79594791-f8e36000-80dd-11ea-9868-472c9452e571.png)

**Comment by Pezzawinkle** [comment]
the stone furnace is on that list, but not the steel furnace? while this is clearly a problem, i don't think that buildGen script is the actual cause...

**Comment by Samuel2507** [comment]
Sorry, thats my bad. The steelt furnace was on that list too when i made the first screenshot

**Comment by Samuel2507** [comment]
The vanilla Burner inserter is affected by this too after the Omnienergy chnages.

Seems to go all the way down to ItemGen()
