### ISSUE TITLE
Omnienergy: Add Miniloader / Loader support

### ISSUE THREAD

**Issue by Samuel2507** [OmnissiahZelos/omnimatter#137]
With Omnienergy, Bob´s Belt overhaul and Miniloaders, the basic Belt is actually cheaper than the Chute.

This is mainly caused by the Belt needing an Omnitor and the Chute recipe not beeing changed.

We could add support for Miniloaders and rebalance the Chute and if necessary, other loader tier aswell

**Comment by SqFKYo** [comment]
Unable to replicate, need more info.
