### ISSUE TITLE
Omnitor assembling machine should use basic fuels

### ISSUE THREAD

**Issue by SqFKYo** [OmnissiahZelos/omnimatter#150]
![image](https://user-images.githubusercontent.com/26864304/80174881-a41f7800-85fc-11ea-9f4b-80a938f854bd.png)
Currently it needs different fuels than burner omnitractor/phlog, which makes it quite useless

**Comment by Samuel2507** [comment]
It was using omnite.
With the latest version its getting overwritten by a new BuildGen script tho
