### ISSUE TITLE
BuildGen:import() resets fuel category, order,sound,...

### ISSUE THREAD

**Issue by Cereal-Sam** [OmnissiahZelos/omnimatter#152]
Using BuildGen:import() on burner entities that have a fuel category != chemical will automatically reset the fuel category back to chemical.

This is happening for the Omnitor assembling machine for example, where the fuel category is now set manually again

![image](https://user-images.githubusercontent.com/62474527/80217312-c71f4b80-863f-11ea-8b38-b93d0dab57eb.png)

Edit: Seems like that theres quite a few other values that get reset aswell (order)

**Comment by Pezzawinkle** [comment]
so the import is not working, its just importing the default stuffs... that should only be happening if those properties were not set (or extended) correctly

**Comment by Cereal-Sam** [comment]
Fuelcat issue got fixed with 02588beb9c787fbf1fa6d9c2a926349b4b0a70a3
