### ISSUE TITLE
earlier compression

### ISSUE THREAD

**Issue by adamcirillo** [OmnissiahZelos/omnimatter#153]
The tech levels for compression seem really quite high especially for marathon playthroughs the old forgeworld mod made it accessible earlier. forgeworld mod removed blue sps from recipe compression and prod sps from compact buildings and mining compression.

**Comment by TokMor** [comment]
I think to have a hope of keeping up with production at omni-marathon + science level of !!FUN!! that compression should start way earlier. I think the compressor machine should be green, Recipe, mining, and compact building 1 should be purple, hand decompression and building 2 should be blue, building 3 orange, building 4 yellow

**Comment by adamcirillo** [comment]
was speaking to infrantryman about the compression @Pezzawinkle he said the techs are fine for a normal playthrough but for marathon seems a bit too much so i'm going to do some code as pr where if compression finds omni science or omni marathon it we reduce the level of sps needed for the techs
