### ISSUE TITLE
[Feature][Omnienergy]Add a second Burner Inserter Tier

### ISSUE THREAD

**Issue by Samuel2507** [OmnissiahZelos/omnimatter#154]
**Is your feature request related to a problem? Please describe.**
Burner Inserters are, like all other early burner entities, in the omnite fuel group and therefor only accept omnite / crushed omnite as fuel.
Burner Inserters are often used for Boiler setups.
Since Boilers only accept Purified Omnite / Omnified Fuel, burner inserters can not be easily used for power setups without running a seperate omnite line to fuel them

**Describe the solution you'd like**
Add a "higher" tier Burner Inserter that accepts Omnified Fuel.
Optional: Buff its stats a bit.

**Comment by SqFKYo** [comment]
I think this makes perfect sense since making separate line to just feed inserters is completely annoying.
