### ISSUE TITLE
Omnipack not getting added to techs with blue sps

### ISSUE THREAD

**Issue by adamcirillo** [OmnissiahZelos/omnimatter#156]
for some reason in the latest dev branch omnipacks are not getting added to blue sp tech. I've done some tests seems related the changes in the latest omniscience update I did. Not sure what has been changed that has caused this. using the rest of the omni mods from dev branch.

**Comment by adamcirillo** [comment]
I've gone over the pr I made and I couldn't find what i changed that would cause this.

**Comment by adamcirillo** [comment]
have reverted changes from @SqFKYo commit here fixed the issue.
https://github.com/OmnissiahZelos/omnimatter/pull/138/commits/2a470a4c973970ca0afaded03c4294db6170d5da

**Comment by SqFKYo** [comment]
Instead of the reverted portion, I probably need to write a function that checks if the tech has golden SP as ingredient and then not assign omnipacks to those techs.

**Comment by adamcirillo** [comment]
without alien sps omnipack is added correctly to all techs
