### ISSUE TITLE
[BUG] Omnitractor's pipe connections are bit off

### ISSUE THREAD

**Issue by SqFKYo** [OmnissiahZelos/omnimatter#159]
**Describe the bug**
Omnitractors/omniphlogs have their graphics not touching the pipes they're connected to.

**To Reproduce**
Plop down omnitractor/omniphlog, witness the graphical glitch.

**Expected behavior**
We should not see break in the graphics.

**Screenshots**
![image](https://user-images.githubusercontent.com/26864304/80306412-d206e700-87cb-11ea-9f26-1a4eae4b1491.png)

**Additional context**
Fairly low priority as it's only graphical glitch.

**Additional Info**
Any version

**Comment by adamcirillo** [comment]
seem to have the same issue with omnismelter from omnichem guessing its the same lib function causing the issue

![image](https://user-images.githubusercontent.com/13363284/80896023-30cce300-8d2d-11ea-9c35-846dc9ecdd66.png)

**Comment by Pezzawinkle** [comment]
This can be fixed in 2 ways... custom fluid-box sprites for each entity, or adding a custom "offset" function to the current sprites

that omnismelter i think needs a rescale, it does not seem to "fit" its box correctly

**Comment by oorzkws** [comment]
I didn't address the omnismelter or energy things. Process should be the same but I'm just not familiar with those entities @Cereal-Sam
