### ISSUE TITLE
Omnimatter Fluid removes Furnace type fluid Output slots

### ISSUE THREAD

**Issue by Samuel2507** [OmnissiahZelos/omnimatter#16]
Omnimatter Fluid removes the Output slot of Furnace type buildings completely instead of converting it into a solid one.

This "Omnicompressor" (furnace) normally has 1 fluid in- and output slot.
After Adding Omnifluid it has no Output slot at all.

![image](https://user-images.githubusercontent.com/62474527/77230880-ceae8900-6b97-11ea-95c8-ca67229112a4.png)

**Comment by Pezzawinkle** [comment]
This is confusing and just plain weird...

**Comment by Samuel2507** [comment]
Can confirm that this is fixex!
