### ISSUE TITLE
[BUG] Omnienergy won't load

### ISSUE THREAD

**Issue by adamcirillo** [OmnissiahZelos/omnimatter#163]
**Describe the bug**
omnienergy won't load

**To Reproduce**
latest deb branch
**Expected behavior**
load factorio

**Screenshots**
![image](https://user-images.githubusercontent.com/13363284/80321119-06c37e80-885e-11ea-9254-f25ab3deb22d.png)

**Additional context**

**Additional Info**
- Factorio Version 18.21
- Modlist / Savegame:
omnimatter dev branch
omnicrystal dev branch
omnienergy dev branch

All Angels latest from mod portal
All Bobs latest from mod portal

**Comment by adamcirillo** [comment]
[_autosave1.zip](https://github.com/OmnissiahZelos/omnimatter/files/4538147/_autosave1.zip)

here is save

**Comment by Samuel2507** [comment]
This is an angels issue replacing calcium-chloride without replacing the .normal and .expensive main_product.
