### ISSUE TITLE
[BUG] Compressed techs locale not showing

### ISSUE THREAD

**Issue by adamcirillo** [OmnissiahZelos/omnimatter#166]
**Describe the bug**
Localization for compressed techs not showing

**Expected behavior**
tech name should be from non compressed tech

**Screenshots**
![image](https://user-images.githubusercontent.com/13363284/80470450-5ea8d500-8985-11ea-9527-6ee3671f2e18.png)

**Additional context**

**Additional Info**
- Factorio Version: 18.18
Omnicompression

**Comment by Pezzawinkle** [comment]
this was a workaround i did a while ago, i didn't get around to actually fixing it.
This should be fixed (at leas appear so) in dev

**Comment by adamcirillo** [comment]
@Pezzawinkle seems the infinite research techs have broken locale still.
![image](https://user-images.githubusercontent.com/13363284/81225299-5c511580-902c-11ea-9d6f-e34eb9169fa6.png)
