### ISSUE TITLE
[BUG] Omnimatter Energy´s custom Power Poles have assembler working sounds

### ISSUE THREAD

**Issue by Samuel2507** [OmnissiahZelos/omnimatter#173]
**Describe the bug**
The  Omnimatter Energy Small iron electric pole and  Small omnicium electric pole have assembler working sounds.

**To Reproduce**
Load up omnimatter energy, playe a small iron electric pole or an small omnicium electric pole
-->They have Assembler working sounds
**Expected behavior**
You hear no working sounds

**Screenshots**
![image](https://user-images.githubusercontent.com/62474527/80858620-a3b95980-8c5a-11ea-88ab-e30f69c94531.png)
![image](https://user-images.githubusercontent.com/62474527/80858622-ad42c180-8c5a-11ea-94bc-7922cf61a396.png)

**Additional context**
This seems realted to BuildGen:import setting default values for things that are nil.
Since the vanilla electric pole gets imported with a working_sound = nil, the default(assembler) sound get set.
Ideally BuildGen:import() should create an exact copy without setting anything else.

**Comment by Samuel2507** [comment]
same issue  with #152

**Comment by Pezzawinkle** [comment]
Requires further testing, but appears to have been fixed

**Comment by Samuel2507** [comment]
Can confirm that this is still an issue

**Comment by Samuel2507** [comment]
Temp fixed with #173

General lib issue described in #152
