### ISSUE TITLE
[BUG] Items that output more than 1 item don't show recipe locale

### ISSUE THREAD

**Issue by adamcirillo** [OmnissiahZelos/omnimatter#175]
**Describe the bug**
A recipe that outputs more than one item usually part of recChain will not show the locale from the item name.

**Expected behavior**
Should display the main product item names for the recipe name

**Screenshots**
![image](https://user-images.githubusercontent.com/13363284/80899449-a2b82300-8d53-11ea-9f89-ff452aa19263.png)

**Additional context**

**Additional Info**
- Factorio Version: 18.22
- Minimal required mods to reproduce:
A omni mod that has a recipe with more than one output

**Comment by SqFKYo** [comment]
Could replicate with omniwater+omnipermute. I assume somehow omnipermute overwrites the localised names.

**Comment by adamcirillo** [comment]
i have just seen this soo with some petrochem recipes with omnifluid no omnipremute. i think this might be an issue with standardization as there are issues with compression too that pez has been looking into.

**Comment by Samuel2507** [comment]
Try to replicate the angel recipe issue without fluid and permute.
Omni recipes arent affected by standardisation in most cases so that should be unrelated.
