### ISSUE TITLE
[BUG] Loading with Omni Logistics and Energy

### ISSUE THREAD

**Issue by szentigrad3** [OmnissiahZelos/omnimatter#177]
![factorio_2020-05-03_17-55-24](https://user-images.githubusercontent.com/5462780/80909372-1f0a3080-8d6b-11ea-9cdf-ea5c31064f7d.png)

loading the game with omni energy and omni logistics creates this error

- Factorio Version: 0.18.21
- Minimal required mods to reproduce: Omni energy, logistics

**Comment by Railgun14234** [comment]
huh, im not the only one having this problem

**Comment by Pezzawinkle** [comment]
@Railgun14234 if you are up for some testing for me, can you please take a look a the new dev version of omnilogistics

**Comment by Railgun14234** [comment]
Sure I'll try it after I wake up, going to bed soon

**Comment by Railgun14234** [comment]
gonna download all of the omnimater mods now, ill let u know if i get any errors

**Comment by Railgun14234** [comment]
![image](https://user-images.githubusercontent.com/59025494/83633785-687fb280-a599-11ea-88a5-198eda40f5de.png)
getting this

**Comment by Railgun14234** [comment]
and this is from a version that i downloaded today, off the github,

**Comment by Railgun14234** [comment]
oh wait, i didnt check for dev version, i just downloaded the master.

**Comment by Railgun14234** [comment]
downloading the dev version

**Comment by Railgun14234** [comment]
by the way, do i need to put in the build.py file in my mods folder?

**Comment by Railgun14234** [comment]
![image](https://user-images.githubusercontent.com/59025494/83635033-6fa7c000-a59b-11ea-9f8b-e12367f6a056.png)
hmm, i hope that this isnt a mod confilct, guess ill diable all other mods that i have and try again, just in case

**Comment by Railgun14234** [comment]
nop, not a mod confilct, im getting the same error even when i only have omnimatter mods enabled

**Comment by Pezzawinkle** [comment]
> by the way, do i need to put in the build.py file in my mods folder?

No, this is not needed.

If those mods are getting circular dependency, they clearly are not publish ready...
