### ISSUE TITLE
Invalid Icon_size definition causing issues with many mods

### ISSUE THREAD

**Issue by Pezzawinkle** [OmnissiahZelos/omnimatter#18]
https://mods.factorio.com/mod/crafting_combinator/discussion/5e746463de88d4000bf619b2
brings up the core issue.
Icon_size should be updated WITH the item/recipe, not in data-final-fixes

**Comment by SqFKYo** [comment]
![image](https://user-images.githubusercontent.com/26864304/77244474-c6009600-6c1d-11ea-956b-0334c36be7ae.png)
Good test case.

**Comment by SqFKYo** [comment]
I'm still getting this issue - Even without omnicompression.

**Comment by Pezzawinkle** [comment]
Can you check that the patch in dev-Icon-Fixes fixes this?

**Comment by Pezzawinkle** [comment]
This should be fixed in the master branch, can i get a second look at this before i close it please

**Comment by Pezzawinkle** [comment]
No further issues for this in a while, ill close it.
