### ISSUE TITLE
[BUG]Integration of omni-water with omni-matter

### ISSUE THREAD

**Issue by TokMor** [OmnissiahZelos/omnimatter#191]
**Describe the bug**
Fluids added by omni-water do not behave like other fluids in base. omni-matter

**To Reproduce**
Add omni-matter, bobs, angels, omni-water.

**Expected behavior**
First, the settings in omniwater are redundant, I recommend that they follow the "number of fluid levels" setting from omni-matter.

Second, only the level 1 tech of omni-water fluids have a tech requirement. Expected result is that they follow the "number of fluid levels per tier" setting and then also act as pre-reqs for omni tractor tech based on the "tier dependency on fluid" setting.

**Screenshots**
Replace this
https://discordapp.com/channels/351216213327609858/351216447919357957/709798448899162234
To use this
https://cdn.discordapp.com/attachments/351216447919357957/709798011294711828/unknown.png

**Additional context**

**Additional Info**
- Factorio Version: 0.xx.xx
- Minimal required mods to reproduce:
- Savegame:

**Comment by Pezzawinkle** [comment]
omnifluid does not rely on omnimatter (unless im mistaken)...
so having the separate setting may be required, but ill add this to the to-do list (adding a project for settings updates)

**Comment by Samuel2507** [comment]
The omniwater techs are now fully integrated into the omni tech tree.
We consider merging the 2 mentioned settings.
