### ISSUE TITLE
Can't craft steel/water

### ISSUE THREAD

**Issue by SqFKYo** [OmnissiahZelos/omnimatter#20]
In full ABCZ you need omniplant to craft water. Omniplant needs BEBs, which needs water.

Most likely we need a burner omniplant that doesn't need BEBs.

Related to #19

**Comment by SqFKYo** [comment]
Found a burner omniplant in omnienergy, need to implement it in omnicrystal.

**Comment by infantryman4life** [comment]
that sounds great @SqFKYo
