### ISSUE TITLE
[BUG][OmniEnegry] "omnitor-lab" doesn't have a fast replace group

### ISSUE THREAD

**Issue by oorzkws** [OmnissiahZelos/omnimatter#211]
Causes a crash with the current dev version. I would PR but I don't know what group would be best.

https://github.com/OmnissiahZelos/omnimatter/blob/fb43ceb6b81e5c530c26573fbd1438cc5fb3ebb2/omnimatter_energy/prototypes/burner.lua#L295

Add, for example,
``
setReplace("lab"):
``
and it solves the issue

**Comment by Samuel2507** [comment]
Cant reproduce, since its a modified vanilla lab version, the fast replacable group is already set

**Comment by Samuel2507** [comment]
Reproducible with pure Z, the vanilla lab has no fast replace group set
