### ISSUE TITLE
Crash on_research_finished (ID 18)

### ISSUE THREAD

**Issue by Neutora** [OmnissiahZelos/omnimatter#215]
The game crashes when you finish the research Artillary Shell Range 1 with the error:
 

2143.469 Error MainLoop.cpp:1207: Exception at tick 23914: The mod Omnicompression (3.18.10) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event omnimatter_compression::on_research_finished (ID 18)
The mod Omnicompression (3.18.10) caused a non-recoverable error.
Please report this error to the mod author.

stack traceback:
	__omnimatter_compression__/control.lua:52: in function <__omnimatter_compression__/control.lua:50>
	[C]: in function '__newindex'
	__omnimatter_compression__/control.lua:65: in function <__omnimatter_compression__/control.lua:50>
	[C]: in function '__newindex'
	__omnimatter_compression__/control.lua:67: in function <__omnimatter_compression__/control.lua:50>
	[C]: in function '__newindex'
	__omnimatter_compression__/control.lua:65: in function <__omnimatter_compression__/control.lua:50>
	[C]: in function '__newindex'
	__omnimatter_compression__/control.lua:67: in function <__omnimatter_compression__/control.lua:50>
	[C]: in function '__newindex'
	...
	__omnimatter_compression__/control.lua:67: in function <__omnimatter_compression__/control.lua:50>
	[C]: in function '__newindex'
	__omnimatter_compression__/control.lua:65: in function <__omnimatter_compression__/control.lua:50>
	[C]: in function '__newindex'
	__omnimatter_compression__/control.lua:67: in function <__omnimatter_compression__/control.lua:50>
	[C]: in function '__newindex'
	__omnimatter_compression__/control.lua:65: in function <__omnimatter_compression__/control.lua:50>
	[C]: in function '__newindex'
	__omnimatter_compression__/control.lua:67: in function <__omnimatter_compression__/control.lua:50>
	[C]: in function '__newindex'
	__omnimatter_compression__/control.lua:65: in function <__omnimatter_compression__/control.lua:50>

It repeats this error a few dozen times.

**Comment by oorzkws** [comment]
Fixed in #216
