### ISSUE TITLE
[BUG]Rocket recipe crash on current portal version

### ISSUE THREAD

**Issue by oorzkws** [OmnissiahZelos/omnimatter#229]
User reported, his rocket silo recipe has no results set so he crashes and can't load. Log with modset attached.

![image](https://user-images.githubusercontent.com/65210810/89481098-3d117380-d754-11ea-8a62-ed8342805930.png)
[factorio-current-1.log](https://github.com/OmnissiahZelos/omnimatter/files/5032049/factorio-current-1.log)

**Comment by Samuel2507** [comment]
Not our fault, that error catches recipes without any result table set.
Error will  probably be gone next version since we reduced standardisation, but this will not solve the core issue that this recipe is corrupted.
