### ISSUE TITLE
[BUG][Compression] Tiered Steam recipes are missing

### ISSUE THREAD

**Issue by TokMor** [OmnissiahZelos/omnimatter#247]
**Describe the bug**
compressed recipes for power do not produce usable results

**To Reproduce**
1. Place down a boiler mk1 or compact boiler mk1
2. Select the compressed recipe to output liquid steam
3. Provide water and fuel
4. "concetrated steam" is produced

**Expected behavior**
a regular boiler mk1 should make normal (not concentrated) steam, as no entity consumes concentrated steam
a compact boiler mk1 should make grade 1 concentrated steam

**Screenshots**
![image](https://user-images.githubusercontent.com/28193512/90586606-99897f80-e1a5-11ea-919f-12e4b984a764.png)
![image](https://user-images.githubusercontent.com/28193512/90586639-a8703200-e1a5-11ea-8f37-a58f60152c86.png)

**Additional context**

**Additional Info**
- Factorio Version: 1.0
- Minimal required mods to reproduce: https://www.dropbox.com/sh/a6lwkzvq6fqafg0/AABg-cumUefE1A1-C1uaYXdPa?dl=0
- Savegame: https://www.dropbox.com/s/55pkym8qzu5bsp8/Omni%20Forge%202020%20Q3.zip?dl=0

**Comment by oorzkws** [comment]
3a96516 in #251 solves the issues not related to omnifluid.
