### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by mecejide** [OmnissiahZelos/omnimatter#253]
It annoys me that crystallology can be used on most, but not all, ores. I’d like to see crystallology chains for the following materials added:
Omnicium plate from omnite
Glass from quartz
Polished ruby from unsorted gemstone ore
Polished sapphire from unsorted gemstone ore
Polished emerald from unsorted gemstone ore
Polished amethyst from unsorted gemstone ore
Polished topaz from unsorted gemstone ore
Polished diamond from unsorted gemstone ore
Lithium from lithia water
Uranium-238 from uranium ore
Chains for different materials from the same ore would diverge at the solvation->crystal stage.
Relevant mods:
Base 1.0.0
Bobplates 1.0.0
Omnimatter_crystal 3.18.8

**Comment by Samuel2507** [comment]
Crystallogy directly outputting plates / processed materials like U-235 breaks balancing with a lot of stuff.
You also miss all secondary outputs you would get from processing the actual ore (like Uranium or all kind of Bob ores).
#295 should solve that
