### ISSUE TITLE
[Feature] Add Py compat to OmniEnergy

### ISSUE THREAD

**Issue by Pezzawinkle** [OmnissiahZelos/omnimatter#261]
**Describe the bug**
Specifically with Py, but may not exclusively be with that mod set...
some early buildings require boilers and steam engines to be crafted as ingredients, so we need to add an ingredient replacement (possibly with the exclusion of tier-up recipes) to allow compatibility.

**To Reproduce**
*known with Py, but may be an issue with other popular mods*

more details to come.

**Comment by Samuel2507** [comment]
Boilers and steam engines are still accessible, just locked behind tech.
So this is rather a missing compat with PY.
If buildings require them as ingredients before you are able to unlock them then we could replace them eventually with turbines

**Comment by szentigrad3** [comment]
https://i.imgur.com/1VUBSq0.jpg > deadlocked behind tech that is not unlocked yet > electric mining drills and inserters

**Comment by Pezzawinkle** [comment]
after a solid review of this, i have made some tweaks to get it functional. These are functional with or without PyTBaA mod.
Currently got it to be playable to at least green tech without PyAL

**Comment by Pezzawinkle** [comment]
Needs further testing by @infantryman4life, or someone vaguely interested in it, before I close this. Since this now runs up to and through the second science pack, I doubt this will be problematic anymore.
