### ISSUE TITLE
Mainlining Omnic Salt Sorting

### ISSUE THREAD

**Issue by SqFKYo** [OmnissiahZelos/omnimatter#27]
Two mods with MIT license might make great addition. Sent a PM to Kremnari to ask what they think about this idea.
https://mods.factorio.com/mod/OmnicSalt_Sorting
https://mods.factorio.com/mod/OmniCrystal_Clowns

**Comment by Pezzawinkle** [comment]
I have already integrated the clowns one into clowns, so that mod is basically depricated.
Im not sure if integrating the omnisalt sorting mod is worth, will keep an open mind though.
