### ISSUE TITLE
[BUG]  no recipe for omnidic salts

### ISSUE THREAD

**Issue by eldon4570** [OmnissiahZelos/omnimatter#279]
**Describe the bug**
the recipe for the omnidic salts (copper omnidic salt, iron omnidic salt, and uranium omnidic salt) do no get generated for me, i can get the items from an infinity chest but cant make them even after /cheat <all>  command.

**To Reproduce**
1. install omni crystal and dependent mods 
2. load game and check recipes (this was done without commands at first)
3. spawn infinity and see that the omnidic salts exist but there is no recipe for them

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/70726814/92180176-0d659200-ee0c-11ea-8d75-0350029bd7b5.png)

**Additional context**

**Additional Info**
- Factorio Version: 1.0.0
- Minimal required mods to reproduce: omnicrystal4.0.1-omnilib4.0.3-omnimatter4.0.2
- Savegame:
[omni bug.zip](https://github.com/OmnissiahZelos/omnimatter/files/5171811/omni.bug.zip)

**Comment by Samuel2507** [comment]
Thank you for your report, this will be fixed with the next update.
