### ISSUE TITLE
Missing Thumbnails

### ISSUE THREAD

**Issue by Samuel2507** [OmnissiahZelos/omnimatter#32]
The following mods have no Thumbnail:

- [x] omnilib
- [x] energy
- [x] chemistry
- [x] research
- [ ] Marathon

The following Thumbnails are missing the purple "Omni" text

- [x] water
- [x] permutation

The following need updating to the new design
- [ ] Compression
- [ ] Science
- [ ] Crystal
- [ ] Fluid
- [ ] Wood

**Comment by SqFKYo** [comment]
Misunderstood, reopening.

**Comment by Pezzawinkle** [comment]
@SqFKYo can you please tick off the list when these are done.

**Comment by Samuel2507** [comment]
Closing this for now since all mod-portal released mods have a thumbnail
