### ISSUE TITLE
[Omnifluid] [BUG] Heat exchanger connects to pipe only when top/left placed

### ISSUE THREAD

**Issue by lictw** [OmnissiahZelos/omnimatter#323]
**Describe the bug**
I think it's critical bug, have big save with this mod, reach the nuclear and can't build normal setup..

**Screenshots**
![1](https://user-images.githubusercontent.com/11904484/108232811-2f519780-7154-11eb-8be7-001e1d225e19.png)

**Additional Info**
- Factorio Version: 1.1

**Comment by Pezzawinkle** [comment]
Heat-pipes... interesting... ill need to check that when I get to that part of the testing.

**Comment by lictw** [comment]
In current version can it be fixed? I'm thinking what me to do on actual save..

**Comment by Pezzawinkle** [comment]
From what I can see, it won't be a quick fix, but we are aware of the underlying problem which is causing the bug.
