### ISSUE TITLE
[BUG] Stack size must be 1 when not_stackable is set

### ISSUE THREAD

**Issue by Garr890354839** [OmnissiahZelos/omnimatter#335]
**Describe the bug**
Stack size must be 1 when not_stackable is set.

**To Reproduce**
1a. Download and enable https://mods.factorio.com/mod/RealisticFusionPower
1b. Download and enable https://mods.factorio.com/mod/omnimatter_compression
2. Run the game

**Expected behavior**
The game to load.

**Additional context**

**Additional Info**
- Factorio Version: 1.1.33
- Minimal required mods to reproduce: Aside from the two listed above, none.
- Savegame: None, as it happens on game load.

**Comment by SqFKYo** [comment]
Fixed on RFP version 1.6.3
