### ISSUE TITLE
Unify mod thumbnails / Recipe subgroup icons

### ISSUE THREAD

**Issue by Cereal-Sam** [OmnissiahZelos/omnimatter#346]
The text "omni" on our thumbnails / Recipe subgroups is different for nearly each mod.
This looks a bit when having all of them next to each other in the inventory tab:
![image](https://user-images.githubusercontent.com/62474527/126800291-e57dc06c-0dab-4cf8-aa52-c3e452b03711.png)

Crystals and wood are the only ones which have the same text size and thickness, altough its hard to read in my opinion (Small and very thick). I would use something close to the omnimatter one, could be a bit bigger if possible.
 
Since these are used as mod thumbnails aswell, we should update the thumbnails that are not used as subgroup icon aswell:
https://mods.factorio.com/user/OmnissiahZelos

**Comment by Pezzawinkle** [comment]
updated, let me know if i need another iteration, i was not sure if we wanted to update the compression category lists either...
