### ISSUE TITLE
[BUG] Angel's Bioprocessing recipes being disabled

### ISSUE THREAD

**Issue by KiwiHawk** [OmnissiahZelos/omnimatter#363]
### Description
Researching tech Desert farming environment is disabling recipes Alien plant-life sample and Desert seed extraction. The same thing is happening for the equivalent Swamp and Temperate recipes / tech.

Researching this tech :
![image](https://user-images.githubusercontent.com/59639/135748803-5f754ef3-9d28-4d2e-9100-dd073accb363.png)
Disables this recipe (`desert-garden-cultivating-a`) :
![image](https://user-images.githubusercontent.com/59639/135748854-cec3b4f3-2141-49da-b9af-df5446f6c773.png)
And this recipe (`desert-garden-a`) :
![image](https://user-images.githubusercontent.com/59639/135748885-d12cdefb-2634-465e-9b5b-3bcc13f6b03e.png)

### Minimum mod list:
- Angel's Bioprocessing
- Angel's Petrochemical Processing
- Angel's Refining
- Angel's Smelting
- Omnilibrary
- Omnimatter

### Cause
I did some debugging. I see that Omnilib is disabling recipes that it detects as being superseded. 

An excerpt from `global.omni.correlated_recipes` :
```lua
  ["desert-garden-a"] = {
    base = "desert-garden-a",
    upgrade = "desert-garden-b"
  },
  ["desert-garden-b"] = {
    base = "desert-garden-b",
    downgrade = "desert-garden-a"
  },
  ["desert-garden-cultivating-a"] = {
    base = "desert-garden-cultivating-a",
    upgrade = "desert-garden-cultivating-b"
  },
  ["desert-garden-cultivating-b"] = {
    base = "desert-garden-cultivating-b",
    downgrade = "desert-garden-cultivating-a"
  },
```

Recipe `desert-garden-cultivating-b` :
![image](https://user-images.githubusercontent.com/59639/135749106-3013254a-d7ad-44b0-8056-d3c8f37ec412.png)

Recipe `desert-garden-b` :
![image](https://user-images.githubusercontent.com/59639/135749133-5d89c5ed-2039-4484-a5c7-57b840b9beca.png)

**Comment by KiwiHawk** [comment]
Workaround, run this script:
``` lua
/c
game.player.force.recipes['swamp-garden-cultivating-a'].enabled = true
game.player.force.recipes['temperate-garden-cultivating-a'].enabled = true
game.player.force.recipes['desert-garden-cultivating-a'].enabled = true
game.player.force.recipes['desert-garden-a'].enabled = true
game.player.force.recipes['swamp-garden-a'].enabled = true
game.player.force.recipes['temperate-garden-a'].enabled = true
```

**Comment by HappyGotLucky** [comment]
Seeing the same problem with our game as well :(

**Comment by oorzkws** [comment]
Please let me know if current dev fixes your issue

**Comment by KiwiHawk** [comment]
Looks good to me!
