### ISSUE TITLE
[BUG] Gun Turret Research is unbalance with Angels Exploration

### ISSUE THREAD

**Issue by 12345swordy** [OmnissiahZelos/omnimatter#380]
**Describe the bug**
Turret Technology is locked behind Military Technology which is makes omniscience more difficult then necessarily,.

**To Reproduce**
OmniEnergy
Angel's Exploration

**Screenshots**
![image](https://user-images.githubusercontent.com/10376365/151263503-888a866e-5ce9-4314-9b22-2a104d7e4c1e.png)

**Comment by Cereal-Sam** [comment]
Thanks for the report, i will take a look at this.
This should indeed not be behind military a red sp tech since that would be way to late for when it is needed

**Comment by Cereal-Sam** [comment]
Moved military to energy science pack only to have some better early defending options
