### ISSUE TITLE
[Feature] Exclude mods from omnicompression when fail to compress while loading factorio

### ISSUE THREAD

**Issue by 12345swordy** [OmnissiahZelos/omnimatter#384]
**Is your feature request related to a problem? Please describe.**
Certain mods are not compatible with Omnicompression. Example of this is [Realistic Fusion Power](https://mods.factorio.com/mod/RealisticFusionPower). 

**Describe the solution you'd like**
If omnicompression fails to compress items from another mod, it better for the omnicompression to skip it the mod or items entirely rather then to crash at the load up phase, and have the user to make a decisions on what mod to pick.

**Additional Info**
OmniCompression
Realistic Fusion Power

**Comment by oorzkws** [comment]
Resolved. For future reference, just report the error - we'll fix it so things can load.
