### ISSUE TITLE
[BUG] Cycle Dependency Bio_industries Omnimatter_wood

### ISSUE THREAD

**Issue by 12345swordy** [OmnissiahZelos/omnimatter#386]
**Screenshots**

![image](https://user-images.githubusercontent.com/10376365/152663323-6deb4e19-01da-4092-b921-0e4d743d8e02.png)

**Comment by Cereal-Sam** [comment]
Hello,
I'm unable to reproduce this. Bio_industries has no dependency on omnimatter_wood and therefor there is no cycle on those two.
There has to be another mod in your pack causing this loop.

**Comment by 12345swordy** [comment]
I believe that I found the culprit here by the process of elimination. The omnipermute mod may cause the loop between bio_industries and omnimatter_wood.

**Comment by 12345swordy** [comment]
[Test.zip](https://github.com/OmnissiahZelos/omnimatter/files/8718593/Test.zip)

**Comment by Cereal-Sam** [comment]
The loop goes over Bio_industries and transport drones:
sciennce-->wood-->Bio_indiustries-->transport_drones-->fluid-->science

We dont really have any depenendies there that we can drop.
I dont know why Bio Industries is dependent on transport drones, that seems wrong to me

**Comment by 12345swordy** [comment]
Removing Omnipermute  causes my modpack to work again.

**Comment by Cereal-Sam** [comment]
As mentioned, the route goes over Bio Industries and Transport drones. (Multiple paths are triggered by this)
Dependencies on our side are fine. I dont see a reason of Bio Industries requiring on transport drones

**Comment by 12345swordy** [comment]
Why then does the removal of omnicompression fixes the issue then? Having omnicompression blacklist certain mods would be very appreciated. (Transport drones does not need to be compress by omnicompresstion as it is a logistics mod).

**Comment by Cereal-Sam** [comment]
Because it breaks the chain.
As said, our dependencies are necessary and the questionable dependency is on Bio Industries side (which has not been updated for a long time)
