### ISSUE TITLE
Omnichem/research: Too interconnected

### ISSUE THREAD

**Issue by SqFKYo** [OmnissiahZelos/omnimatter#4]
Currently the three mods seem to be completely interlocked. Should be able to load one without needing all. Makes debugging very hard. Currently not sure where to start.

**Comment by SqFKYo** [comment]
Experimental omni, might get abandoned, so wontfix for now.

**Comment by SqFKYo** [comment]
Omnienergy is now untangled! Chem/research left to untangle or merge together.

**Comment by adamcirillo** [comment]
Omnichem loads fine on its own. Planning to use it for crystal circuits in crystal https://github.com/OmnissiahZelos/omnimatter/issues/176. So you can close the issue if you want now.

**Comment by SqFKYo** [comment]
Sounds like it's solved then, thank you!
