### ISSUE TITLE
Check Naming scheme of Buildings

### ISSUE THREAD

**Issue by Samuel2507** [OmnissiahZelos/omnimatter#40]
The different Tiers of Buildings are named differently in Omni Mods.
All Omnimatter Buildings with Tiers are named "... MK X".
In Omnicrystal its for example  just "... X".

When refactoring code or working on the locals this should be checked.

The following Mods have been checked:

- [x] omnilib
- [x] omnimatter
- [x] chemistry
- [x] compression
- [x] crystal
- [x] energy
- [x] fluid
- [x] permutation
- [x] research
- [x] science
- [x] water
- [x] wood

**Comment by adamcirillo** [comment]
I did this with the omnichem pr i sent to dev the other day
