### ISSUE TITLE
Angel's Bio Seed recipes show wrong Seedling 

### ISSUE THREAD

**Issue by SqFKYo** [OmnissiahZelos/omnimatter#44]
![image](https://user-images.githubusercontent.com/26864304/77570818-08073180-6ed5-11ea-90c7-4be32f336011.png)
Recipe uses omnifused seedlings when Bob's Greenhouse, Angel's Bio and Omniwood are present, but the icon on the recipe is still regular Seedling. Same issue for all seeds (12 recipes total).

**Comment by Pezzawinkle** [comment]
found typo, updated
