### ISSUE TITLE
Omnimatter needs Omnicrystal (or other mods...) to load

### ISSUE THREAD

**Issue by SqFKYo** [OmnissiahZelos/omnimatter#48]
While fixing Omnisludge's continuity, I broke omnimatter's omnitractor-electric-2 tech:
![image](https://user-images.githubusercontent.com/26864304/77620835-ebeea900-6f43-11ea-9144-24cd5665caa1.png)

**Comment by SqFKYo** [comment]
The issue comes up if you load only omnilib and omnimatter without other omnimods it seems.

**Comment by Pezzawinkle** [comment]
Found the issue, try not to add tech pre-requisites from other mods without putting a check in first please.
