### ISSUE TITLE
Supersized icons

### ISSUE THREAD

**Issue by SqFKYo** [OmnissiahZelos/omnimatter#5]
![image](https://user-images.githubusercontent.com/26864304/76658403-bb3e6500-657c-11ea-903d-f6db77307291.png)
Some icons get supersized for some reason.

**Comment by infantryman4life** [comment]
omnipack, red, green, blue and many other icons are supersized. i think its one of the mods that causes it. not omnilib, omni compression or omnimatter

**Comment by SqFKYo** [comment]
Works with new omnicompression, but doesn't without.

**Comment by Pezzawinkle** [comment]
Merged branch into master, icon issues should now be fixed on all major omnimods
