### ISSUE TITLE
Omnifluid loading error

### ISSUE THREAD

**Issue by szentigrad3** [OmnissiahZelos/omnimatter#54]
![factorio_2020-03-28_14-14-10](https://user-images.githubusercontent.com/5462780/77813736-15076900-70ff-11ea-8482-485d125e1a29.png)

**Comment by Pezzawinkle** [comment]
Ah, that was my bad, when i moved a function (part of) out of that file i didn't call it back into the file.
Ill test and push a fix to my dev branch today.
