### ISSUE TITLE
Naming changes to omnimods

### ISSUE THREAD

**Issue by SqFKYo** [OmnissiahZelos/omnimatter#58]
I really like the Bob's style of naming mods: 0.factorioversion.own_version. Should we do that as well? Might be easier to distinguish what version we're talking about.

**Comment by Pezzawinkle** [comment]
im not sure we can realistically go "backwards", so i think leaving on on Gen 3, then start at 18 is fine
name_3.18.0 is not a bad way to release them for 0.18, nothing is that high anyway.
Make a note in the changelogs regarding the name style change.

**Comment by Samuel2507** [comment]
Implemented with #78
