### ISSUE TITLE
Angel's refining + omnicrystal doesn't load

### ISSUE THREAD

**Issue by SqFKYo** [OmnissiahZelos/omnimatter#60]
![image](https://user-images.githubusercontent.com/26864304/77856324-03a58600-71ff-11ea-9375-4dd6d2a4fc16.png)

**Comment by SqFKYo** [comment]
To fix you need:
Bob's functions
Bob's Logistics
Bob's Metals, Chemicals and Intermediates (bobsplates)
Bob's Ores
If you remove any single of those mods, it will crash.

**Comment by SqFKYo** [comment]
Update: Most likely Angel's issue -> Might be ready to release!

**Comment by Pezzawinkle** [comment]
Angel gives a dummy recipe if it "fails", it may be worth doing the same here, then at least it will load ;)

**Comment by Pezzawinkle** [comment]
I have updated omnicrystal to load under more conditions, not sure if you want to pull my fix just yet.
