### ISSUE TITLE
Crushed Stone Icon missing without Angels

### ISSUE THREAD

**Issue by Samuel2507** [OmnissiahZelos/omnimatter#61]
Without Angels Omnimatter just uses the Vanilla Stone Icon for crushed Stone which is a bit confusing ingame.

**Comment by Pezzawinkle** [comment]
What was the exact combination for this? I don't seem to be able to replicate this issue.
There are a few recipes that produce stone AND crushed stone

**Comment by Samuel2507** [comment]
Pure Vanilla with omnimatter.
Normally Angels Refining adds the crushed Stone item+Icon.
But if Angels isnt present Omni adds Crushed Stone and just uses the vanilla Stone Icon for it
