### ISSUE TITLE
OmniCompression Loading error with Picker Cheats

### ISSUE THREAD

**Issue by szentigrad3** [OmnissiahZelos/omnimatter#64]
![factorio_2020-03-30_12-09-21](https://user-images.githubusercontent.com/5462780/77866596-78200980-727f-11ea-92fe-48a51fc345fc.png)

**Comment by SqFKYo** [comment]
Not prioritizing in fixing until the bugs within ABCZ domain are fixed.

**Comment by SqFKYo** [comment]
Picker cheats is deprecated, not fixing.
