### ISSUE TITLE
OmniFluid loading error with Crafting Combinator

### ISSUE THREAD

**Issue by SqFKYo** [OmnissiahZelos/omnimatter#68]
![image](https://user-images.githubusercontent.com/26864304/77895110-f7f9a400-727e-11ea-9ad8-42693ca01d9c.png)

Fixing AFTER post-0.18 release unless it's easy and gets tackled along the way.

**Comment by szentigrad3** [comment]
https://github.com/OmnissiahZelos/omnimatter/blob/master/omnimatter_fluid/prototypes/sluids-generation.lua#L61
The issue is that the icon path is supposed to be at key icon, but it's just as an array

**Comment by szentigrad3** [comment]
can confirm its been fixed
