### ISSUE TITLE
Omnifused seedling has no usage in some scenarios

### ISSUE THREAD

**Issue by infantryman4life** [OmnissiahZelos/omnimatter#7]
i can build it but i cant use it.

**Comment by SqFKYo** [comment]
Currently omniwood removes their use if both Bob's Greenhouse and Angel's Bio are present. Thinking about implementing some longer path with Angel's Arboretum to have omnilike experience.

**Comment by infantryman4life** [comment]
well that sounds good :)

**Comment by SqFKYo** [comment]
The gist:
Remove Bob's recipes
Change Tree -> Wood into Tree -> Omnifused Wood
Change Seedlings into Omnifused Seedlings
Remove the Tree Seed -> Omnifused Wood recipe.

**Comment by SqFKYo** [comment]
Closed by #42
