### ISSUE TITLE
Transport_Drones causing crash

### ISSUE THREAD

**Issue by SqFKYo** [OmnissiahZelos/omnimatter#80]
![image](https://user-images.githubusercontent.com/26864304/78235853-e8c66080-74e1-11ea-92b9-857187355a69.png)
Minimum set: 
Omniscience
Omnimatter
Transport Drone
Pez's hunch:
if mods["omnimatter_crystal"] then
  data.raw.tool["production-science-pack"].icon = "__omnimatter_science__/graphics/icons/production-science-pack.png"
  data.raw.tool["omni-pack"].icon_size=64
  data.raw.recipe["omni-pack"].icon_size=64
end

**Comment by SqFKYo** [comment]
Another example.
![image](https://user-images.githubusercontent.com/26864304/78239083-fa116c00-74e5-11ea-810e-2d34bd7e5f37.png)

**Comment by Samuel2507** [comment]
Fixed in DEV
