### ISSUE TITLE
Unknown Key errors in mod settings

### ISSUE THREAD

**Issue by veladon** [OmnissiahZelos/omnimatter#82]
Unknown key errors in mod settings:

![2](https://user-images.githubusercontent.com/15131572/78246821-aa30a600-74e1-11ea-9410-cd6e79c33bb7.png)
![1](https://user-images.githubusercontent.com/15131572/78246822-aac93c80-74e1-11ea-8855-4fa67dfaa88e.png)

**Comment by Pezzawinkle** [comment]
also missing the omnilib auto-update setting localisation
