### ISSUE TITLE
Omnicompressesion leaves compressed tech in tree

### ISSUE THREAD

**Issue by adamcirillo** [OmnissiahZelos/omnimatter#98]
When you have researched a normal tech you can still research the compressed version of it.

![image](https://user-images.githubusercontent.com/13363284/78508031-2ddee100-77c7-11ea-9c16-ada2b7dd7185.png)

**Comment by Pezzawinkle** [comment]
This looks like it could be part of the omnilib control file

**Comment by adamcirillo** [comment]
I've noticed further into this the compressed techs are researched on game loading the save

**Comment by Pezzawinkle** [comment]
so the unlocked techs are updating on game load? but not on tech completed... well that narrows down which part of the control file needs to be looked at for compression.
